### ISSUE TITLE
Async Web Requests

### ISSUE THREAD

**Issue by TobeTek** [Amatobahn/FigmaPy#8]
Hello!
Great project you've got here. I found it quite useful in a pet project of mine, so first of all, many thanks. 

I was wondering if we could add support for asynchronous web requests? I'd be happy to make a PR if it's something you consider reasonable.
I've been working on a Python project of mine, *[servus](https://github.com/TheDynamics/servus)*, that makes aiohttp's syntax a little more human-friendly as well. I think that would be a perfect fit for this.

PS: Is there a function to "recursively" walk through all the elements in a document? I couldn't seem to find one, could you point me in the right direction?

**Comment by hannesdelbeke** [comment]
Hey thanks for joining :) 

1. async was on the list eventually. if you add a PR that be ace.
worth considering if it's possible to do this without adding a dependency to another module though.

2. there are a few recursive functions.
- Node.get_children_recursively
- Paint.root_parent (still in PR)

```python
figmaPy = FigmaPy.FigmaPy(auth_key)
file = figmaPy.get_file(file_key)
page1 = file.document.children[0]
nodes = page1.get_children_recursively()
```
this lists all nodes in the page

**Comment by TobeTek** [comment]
Hello @hannesdelbeke, thanks for responding. 

More on asynchrony, what do you think would be the best implementation?
From my perusal of the codebase, [FigmaPy](https://github.com/Amatobahn/FigmaPy/blob/2fb6d22c680bd13b220c3e758d381a1309073be1/FigmaPy/figmapy.py#L7) is responsible for web requests, we could

1. Create a new class, `AsyncFigmaPy` that implements async versions of all the methods of `FigmaPy`. There would be a lot of code duplication, but future refactors could streamline that. This seems the easiest/quickest to achieve with minimal change to the codebase.
2. Change all existing methods of `FigmaPy` to async and create synchronous wrapper methods for traditional use. A little more effort, but much easier to maintain. 

[Here's a question from SO that provides a bit of context](https://stackoverflow.com/a/55365529)

**Comment by hannesdelbeke** [comment]
ideally sync methods have no async dependencies.
your second proposal seems it'll import async modules , preventing a pure sync only setup? 

your first proposal sounds good. 
Does this sum up the refactor you mention ? : 
Move the code that doesn't use requests out the sync methods to shared helper functions which can be reused in async methods?

How much work would it be to mock up a PR:
figmapy_async.py
class FigmaPyAsync
with a single async method. let's say def get_file_images

note it might make sense to name the class after the async implementation.
ex. FigmaPyAsyncio or FigmaPyCurio
allowing a clear distinction in casse someone else wants to make a different async version later.

from the [article](https://stackoverflow.com/questions/55152952/duplication-of-code-for-synchronous-and-asynchronous-implementations/55365529#55365529) you linked, this seems to fall under the point
"Opt2. (sensible) partial refactor, let e.g. async library depend on and import sync library."
but instead of 2 libraries, we use 2 python classes. FigmaPy & FigmaPyAsync. 
since the rest of our library doesnt use requests, it can be shared.

**Comment by TobeTek** [comment]
Just created a PR to illustrate some ideas. Do have a look.

I did think about the async dependency imports, but I've seen other packages handle them with a `try/except`, So that's what I did.

After some more time on the codebase, looks like most of the code builds URL strings through concatenation or similar. I attempted a basic refactor to `get_file`, `get_file_nodes`,  and `get_file_images` . 

I settled on [aiohttp](https://docs.aiohttp.org/en/latest/web_exceptions.html) because of speed. [(Reference article)](https://github.com/encode/httpx/issues/838)
